App auto scaling scalable targets
rebuy-de/aws-nuke pull request #564
Opened 2020-10-03 21:24 UTC by travismsmith

Added scalable targets similar to #489 but with dynamic namespaces using ServiceNamespace_Values()

2021-02-05 11:34 UTC, der-eismann requested changes

2021-02-05 11:34 UTC, der-eismann commented on resources/applicationautoscalingscalabletargets.go
> +	properties.Set("ScalableDemension", a.dimension)
```suggestion
	properties.Set("ScalableDimension", a.dimension)
```

2021-02-05 11:34 UTC, der-eismann commented
Could you also rebase your branch? We introduced a new CI system that your branch needs to pick up.

2021-03-26 13:29 UTC, svenwltr commented
Closing, because it is outdated. Please reopen, if this is still desired.

2021-03-26 13:29 UTC, closed without merging