added pages and properties to IAMPolicy
rebuy-de/aws-nuke pull request #580
Opened 2020-12-03 01:13 UTC by mrkenkeller

As mentioned in #572 I added a properties function and a few attributes into line with other IAM resources, and also changed the string function to display the name and not the ARN.

2020-12-03 08:58 UTC, svenwltr requested changes

2020-12-03 08:58 UTC, svenwltr commented on resources/iam-policies.go
> +	return e.name
You cannot change the `String` output, as this would break existing aws-nuke configs.

2020-12-03 08:58 UTC, svenwltr commented on resources/iam-policies.go
> +	//resp, err := svc.ListPolicies(params)
Please remove.

2021-01-13 16:20 UTC, der-eismann submitted a review, later dismissed

2021-01-13 16:21 UTC, der-eismann commented
Please rebase your branch on master since we changed our CI system.

2021-01-14 23:39 UTC, mrkenkeller commented
> Please rebase your branch on master since we changed our CI system.

Should be good - still learning details of git, so let me know!

2021-01-31 22:34 UTC, closed without merging