Added disable feature for cognito-user-pool deletion protection
rebuy-de/aws-nuke pull request #993
Opened 2023-05-07 11:24 UTC by suleman-sohail

Title is descriptive

2023-05-08 06:54 UTC, farrukh-taqveem reviewed
Let's remove these un-necessary lines & spaces. 
Rest Looks good.

2023-05-08 06:54 UTC, farrukh-taqveem commented on pkg/config/config.go
> +	CognitoUserPool 	bool `yaml:"CognitoUserPool"`
```suggestion
	CognitoUserPool bool `yaml:"CognitoUserPool"`
```

2023-05-08 06:54 UTC, farrukh-taqveem commented on resources/cognito-userpools.go
> +
```suggestion
```

2023-05-08 06:54 UTC, farrukh-taqveem commented on resources/cognito-userpools.go
> +
```suggestion
```

2023-05-18 12:10 UTC, farrukh-taqveem approved these changes

2023-07-20 15:28 UTC, npellegrin commented
Hello. I am also looking forward to have this feature in aws-nuke. Does this Merge request require additional fixes I can help with ?

2023-07-20 16:10 UTC, npellegrin commented
References #993

2023-07-25 17:28 UTC, suleman-sohail commented
> Hello. I am also looking forward to have this feature in aws-nuke. Does this Merge request require additional fixes I can help with ?

Nope, I believe we are all set for the referenced issue, we can get this merged.

2023-08-02 08:34 UTC, bjoernhaeuser commented on resources/cognito-userpools.go
> +			if err!=nil{
Can you please quickly run `go fmt` on these files?

2023-08-25 15:26 UTC, der-eismann requested changes

2024-04-15 18:20 UTC, BrutalSimplicity commented
Ran into this issue today. It looks like this is pending some updates from the author @suleman-sohail. If they're unable to get to this, should a new PR be opened? It doesn't look like much is left here but some cosmetic changes.

2024-04-19 15:34 UTC, suleman-sohail commented
> Ran into this issue today. It looks like this is pending some updates from the author @suleman-sohail. If they're unable to get to this, should a new PR be opened? It doesn't look like much is left here but some cosmetic changes.

Hi, I could not reply anytime soon, thanks for waiting. I believe I was able to address the relevant comments, I might have miss something. You can create PR on child branch of this one, do any changes you think are needed for this PR to get merged, get that merged in this one, and we are good to go.

2024-09-04 09:51 UTC, malc-moo approved these changes

2024-09-04 09:52 UTC, malc-moo approved these changes

2024-09-26 21:57 UTC, ekristen commented
This was implemented in the fork via this PR https://github.com/ekristen/aws-nuke/pull/311 and is in 3.23.0 and forward.

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

2024-09-26 21:57 UTC, closed without merging